"""
This module provides functionality for calculating Revolutions Per Minute (RPM)
using a hall effect sensor connected to a Raspberry Pi GPIO pin. It calculates
RPM based on time intervals between ABS pulses generated by magnetic sensors.

Classes:
- RPMClass: Handles RPM calculation and management, including GPIO setup.

This module is designed to be used in electronics projects where monitoring
rotation speed is required, such as in wheels or motors.
"""

import datetime
from RPi import GPIO
from app_control import settings
from logmanager import logger


class RPMClass:
    """
    Encapsulates the functionality for calculating and monitoring RPM (Revolutions Per Minute) using
    a hall effect sensor and GPIO pins.

    This class is designed to handle RPM calculations for a rotating object by monitoring signals from
    a hall effect sensor connected to specific GPIO pins. It uses a rolling average to provide smooth
    RPM readings and includes mechanisms to handle signal timeouts, making it suitable for real-time
    applications where RPM data is critical. The class also provides access to detailed pulse interval
    data for further analysis.

    Attributes:
        magnets: int
            The number of magnets on the wheel per revolution.
        rev_average: int
            The rolling average of revolutions used for RPM calculations.
        gpio_line: Any
            The GPIO pin to which the hall effect sensor is connected.
        rpm_timeout: Any
            The timeout duration in seconds, used to detect when a signal is considered stale.
        timequeuesize: int
            The size of the rolling queue for time intervals between pulses.
        timequeue: list
            A rolling time-based queue that stores timestamps of pulses for RPM calculations.
    """
    def __init__(self):
        self.magnets = settings['rpm_magnets']  # no of magnets on the wheel per revolution
        self.rev_average = 3  # rolling average revolutions
        self.gpio_line = settings['rpm_sensor_GPIO']  # line used for the hall effect device
        self.rpm_timeout = settings['rpm_timeout_seconds']
        self.timequeuesize = self.magnets * self.rev_average
        self.timequeue = []
        GPIO.setmode(GPIO.BCM)  # set the GPIO to use Broadcom channel numbering
        GPIO.setup(self.gpio_line, GPIO.IN)  # set the input sensor
        GPIO.add_event_detect(self.gpio_line, GPIO.RISING,
                              callback=self.recievedpulse, bouncetime=10)
        GPIO.setup(settings['rpm_active_LED'], GPIO.OUT)  # set running LED channel
        GPIO.output(settings['rpm_active_LED'], GPIO.HIGH)  # switch on running LED

    def __del__(self):
        """
        Cleans up resources and performs necessary actions before the object is destroyed.

        This method is invoked automatically when the object is about to be destroyed. It ensures
        that any allocated resources are released and hardware is properly cleaned up.

        Raises:
            None
        """
        logger.debug("RPM deleted")
        GPIO.cleanup()

    def recievedpulse(self, pin):   # pylint: disable=W0613
        """
        Records the occurrence of a pulse and maintains a queue of timestamps up to the defined size.

        The method appends the current timestamp to the queue of recorded events when it is called.
        If the number of timestamps in the queue exceeds the allowed queue size, it removes the
        oldest timestamp to maintain the queue length.

        Parameters:
            pin (Any): The input pin where the pulse is detected. This parameter is not currently used.

        """
        self.timequeue.append(datetime.datetime.now())
        # print(self.timequeue)
        if len(self.timequeue) > self.timequeuesize:
            self.timequeue.pop(0)

    def get_rpm(self):
        """
        Calculates and returns the revolutions per minute (RPM) based on the time difference
        between the first and last elements in the time queue. The method ensures that the
        RPM is computed only if the time queue contains the required number of elements
        defined by `timequeuesize`. If the time queue contains outdated elements beyond
        a specified timeout (`rpm_timeout`), it removes the oldest element.

        Parameters:
            None

        Returns:
            float: The calculated RPM value if the time queue is of the required size.
                   Returns 0 if the time queue does not have the required number of elements.
        """
        if len(self.timequeue) == self.timequeuesize:
            rev = 60 / ((self.timequeue[self.timequeuesize - 1]
                         - self.timequeue[0]).total_seconds() / self.rev_average)
            # print('%s RPM' % rev)
            if (datetime.datetime.now() - self.timequeue[self.timequeuesize - 1]).total_seconds()\
                    > self.rpm_timeout:
                self.timequeue.pop(0)
            return rev
        return 0

    def get_rpm_data(self):
        """
        Returns RPM data as a list of time intervals.

        The function computes and returns a list of time intervals in seconds, where each
        interval represents the difference between the first timestamp in the time queue
        and the subsequent timestamps. The length of the result corresponds to one more
        than the number of magnets due to the inclusion of the initial timestamp.

        Returns:
            list[float]: A list of time intervals in seconds, where each interval is
            calculated as the difference between the first timestamp and the subsequent
            timestamps in the `timequeue` attribute.
        """
        returntime = []
        for i in range(self.magnets + 1):
            returntime.append((self.timequeue[i] - self.timequeue[0]).total_seconds())
        return returntime


if __name__ == '__main__':  # used for standlone testing
    rpm = RPMClass()
    X = True
    while X:
        X = input('any key to continue')
        print(f'RPM={rpm.get_rpm()}')
    GPIO.cleanup()
